# Generated by Django 5.2 on 2025-04-19 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
