# Generated by Django 5.2 on 2025-06-03 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0011_likedreply_reply_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
    ]
